name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:-dev
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  deploy-dev:
    name: Deploy Dev
    runs-on: ubuntu-lastest
    environment: env-dev
    needs: [build-dev]
    steps:
      - name: Teste
        run: echo Deploy Dev
  deploy-qa:
    name: Deploy QA
    runs-on: ubuntu-lastest
    environment: env-qa
    needs: [deploy-dev]
    steps:
      - name: Teste QA
        run: echo Deploy QA


