name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-dev:
    name: Build Dev
    runs-on: ubuntu-latest
    steps:
      - id: bds1
        name: Run a one-line script
        run: echo Hello, world!
      - id: bds2
        name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  deploy-dev:
    outputs:
      status: ${{ join(steps.*.conclusion) }}
    name: Deploy Dev
    runs-on: ubuntu-lastest
    environment: env-dev
    needs: [build-dev]
    steps:
      - id: dds1
        name: Teste
        run: echo Deploy Dev
      - id: dds2
        name: Teste 2
        run: echo Deploy Dev 2
  work-dev:
    name: Work Dev
    runs-on: ubuntu-lastest
    needs: deploy-dev
    if: contains(needs.deploy-dev.outputs.status, failure())
    steps:
      - run: echo Erro Work Dev
  deploy-qa:
    name: Deploy QA
    runs-on: ubuntu-lastest
    environment: env-qa
    needs: [deploy-dev]
    steps:
      - name: Teste QA
        run: echo Deploy QA


