name: CI-QA

on:
  workflow_dispatch:

jobs:
  build_qa:
    name: Build QA
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  deploy-qa:
    name: Deploy QA
    runs-on: ubuntu-lastest
    environment: env-qa
    needs: [build_qa]
    steps:
      - name: Teste
        run: echo Deploy Dev
